<?php

$literales = array(
    'permisoSHOW'=>'Estos son los datos del perfil ',
    'permisoMODIFY'=>'Estos son los datos del perfil: ',
    'permisoDELETE'=>'¿ Esta seguro que desea eliminar este Permiso ?',
    'seleccion accion'=>'Seleccion la acción',
    'seleccion controlador'=>'Seleccione el controlador',
    'seleccion perfil'=>'Seleccione el perfil',
    'permisoADD'=>'Indique los parametros del nuevo perfil',
    'usuarioSHOW'=>'Este son los datos del Usuario',
    'usuarioMODIFY'=>'Estos son los datos del Usuario',
    'usuarioADD'=>'Indique los datos del nuevo Usuario ',
    'usuarioDELETE'=>'¿ Esta seguro que desea eliminar el Usuario ?',
    'perfilSHOW'=>'Este son los datos del Perfil',
    'perfilMODIFY'=>'¿Esta seguro que desea modificar el Perfil?',
    'perfilADD'=>'Indique el nombre del nuevo Perfil',
    'perfilDELETE'=>'¿ Esta seguro que desea eliminar el Perfil ?',
    'accionSHOW'=>'Este son los datos de la Acción',
    'accionMODIFY'=>'¿Esta seguro que desea modificar la Acción?',
    'accionADD'=>'Indique el nombre de la nueva Acción',
    'accionDELETE'=>'¿ Esta seguro que desea eliminar esta Acción ?',
    'datosControlador'=> 'Estos son los datos del controlador',
    'volver'=>'<< Volver',
    'confirmar borrado'=>'¿Esta seguro que desea borrar el usuario? ',
    'modificar'=>'Modificar',
    'cancelar'=>'Cancelar',
    'eliminar'=>'Eliminar',
    'eliminar usuario'=>'Eliminar usuario',
    'seleccion perfil'=> 'Seleccion del perfil:',
    'bienvenida' => 'Nos alegramos de verte de nuevo',
    'editar usuario'=>'Editar usuario',
        'nombre'=>'Nombre',
        'apellido'=>'apellido',
        'dni'=>'DNI',
        'password'=>'Password',
        'perfil'=>'Perfil',
        'accion'=>'Acción',
        'usuarios'=>'USUARIOS',
        'gestion' => 'GESTIÓN',
        'alta usuario'  =>'Alta usuario',
        'idioma'=> 'Seleccione el idioma',
        'nuevo usuario'=>'NUEVO USUARIO',
        'enviar'=>'Enviar',
        'reset'=>'Resetear',

)
?>